for ($i = 1; $i -lt 81; $i++) {
    echo "random.seed 897464313" >> "config-algoJL-$i.txt"
    echo "simulation.endtime 100000" >> "config-algoJL-$i.txt"
    echo "network.size 32" >> "config-algoJL-$i.txt"
    echo "protocol.transportPID UniformRandomTransport" >> "config-algoJL-$i.txt"
    echo "protocol.transportPID.mindelay 1" >> "config-algoJL-$i.txt"
    echo "protocol.transportPID.maxdelay 1" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL peersim.AlgoJL" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL.tr transportPID" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL.nb_resource 80" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL.nbCS -1" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL.nb_max_r_asked $i" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL.min_cs 5" >> "config-algoJL-$i.txt"
    echo "protocol.algoJL.max_cs 35" >> "config-algoJL-$i.txt"
    echo "init.algoJLInit peersim.InitJL" >> "config-algoJL-$i.txt"
    echo "init.algoJLInit.jl algoJL" >> "config-algoJL-$i.txt"
    echo "init.algoJLInit.min 2" >> "config-algoJL-$i.txt"
    echo "init.algoJLInit.max 3" >> "config-algoJL-$i.txt"
}